[build]
command = "hugo --gc --minify"
publish = "public"
[build.environment]
HUGO_BASEURL = "/"
HUGO_THEME = "repo"
HUGO_VERSION = "0.88.1"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.88.1"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.88.1"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.88.1"
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
