[build]
command = "hugo --minify --gc"
publish = "public"
[build.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
