[build]
command = "hugo --minify --gc"
publish = "public"
[build.environment]
HUGO_BASEURL = "/"
HUGO_VERSION = "0.87.0"
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
