[build]
command = "cd exampleSite && hugo --minify --gc --themesDir ../.."
publish = "exampleSite/public"
[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
